import { TabInfo } from "../types/tabs";

export const tabs: TabInfo[] = [
  {
    title: "Suzume",
    source: "Suzume no Tojimari",
    artist: "RADWIMPS",
    videoLink: "https://youtu.be/wQANVR4vqXI",
    genre: "Anime",
    tuning: {
      name: "Open D#maj7",
      strings: ["D#", "G", "D", "G", "A#", "D"],
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0268543",
    },
    guitardex: "https://gdex.cc/?Suzume_14.5.17.1.2.4.16.6.7.10.11.12.22",
    difficulty: 4,
  },
  {
    title: "I Really Want to Stay At Your House",
    source: "Cyberpunk: Edgerunners",
    artist: "Rosa Walton, Hallie Coggins",
    videoLink: "https://youtu.be/DGtyrC2Xn3g",
    genre: "Anime/Game",
    tuning: {
      name: "Open A#maj7",
      strings: ["A#", "F", "D", "F", "A", "F"],
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0268403",
    },
    difficulty: 6,
  },
  // {
  //   title: "Krone",
  //   source: "Guilty Crown",
  //   artist: "Hiroyuki Sawano",
  //   videoLink: "https://youtu.be/9JOwtlOqXIA",
  //   genre: "Anime",
  //   difficulty: 0,
  // },
  // {
  //   title: "Die For You",
  //   artist: "Joji",
  //   videoLink: "https://youtu.be/c-LBF9aST7Q",
  //   genre: "R&B",
  //   difficulty: 0,
  // },
  // {
  //   title: "Anti-Hero",
  //   artist: "Taylor Swift",
  //   videoLink: "",
  //   genre: "Pop",
  //   difficulty: 0,
  // },
  // {
  //   title: "Glimpse of Us",
  //   artist: "Joji",
  //   videoLink: "https://youtu.be/mgxGC2GP3Do",
  //   genre: "R&B",
  //   difficulty: 0,
  // },
  // {
  //   title: "Shiver",
  //   source: "Mushishi Zoku Shou",
  //   artist: "Lucy Rose",
  //   videoLink: "https://youtu.be/0qIkm6BOPCY",
  //   genre: "Anime",
  //   difficulty: 0,
  // },
  // {
  //   title: "Bella Ciao",
  //   source: "La casa de papel (Money Heist)",
  //   artist: "Manu Pilas",
  //   videoLink: "https://youtu.be/umVfZVUFt_k",
  //   genre: "TV/Movie",
  //   difficulty: 0,
  // },
  {
    title: "Make You Feel My Love",
    source: "",
    artist: "Bob Dylan",
    videoLink: "https://youtu.be/sThWUbjevjE",
    genre: "Rock",
    tuning: {
      name: "Standard",
      strings: ["E", "A", "D", "G", "B", "E"],
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0254688",
    },
    difficulty: 5,
  },
  {
    title: "The Rumbling",
    source: "Attack on Titan: Final Season Part 2",
    artist: "SiM",
    videoLink: "https://youtu.be/6Obd-qh9LJU",
    genre: "Anime",
    tuning: {
      name: "Open G/D#",
      strings: ["D#", "G", "D", "G", "B", "D"],
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0253775",
    },
    difficulty: 6,
  },
  {
    title: "Enemy",
    source: "Arcane",
    artist: "Imagine Dragons",
    videoLink: "https://youtu.be/_ZG7Q5SgD9s",
    genre: "TV/Movie",
    tuning: {
      name: "Open G/D#",
      strings: ["D#", "G", "D", "G", "B", "D"],
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0253634",
    },
    difficulty: 5,
  },
  {
    title: "Red Light, Green Light, Way Back Then, I Remember My Name, Unfolded",
    source: "Squid Game Medley",
    artist: "Jung Jae-il",
    videoLink: "https://youtu.be/LYcM1QIxmLA",
    genre: "TV/Movie",
    tuning: {
      name: "Open Cm",
      strings: ["C", "G", "C", "G", "C", "D#"],
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0243443",
    },
    difficulty: 4,
  },
  {
    title:
      "Hello, Good for You, Love Me Like You Do, Flashlight, Lean On, Waiting for Love, See You Again, Take Me to Church, Drag Me Down, Thinking Out Loud",
    source: "2015 Medley",
    artist:
      "Adele, Selena Gomez, Ellie Goulding, Jessie J, Major Lazer, Avicii, Wiz Khalifa, Hozier, One Direction, Ed Sheeran",
    videoLink: "https://youtu.be/T5trmYRacAE",
    genre: "Medley",
    tuning: {
      name: "Standard",
      strings: ["E", "A", "D", "G", "B", "E"],
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0243661",
    },
    difficulty: 6,
  },
  {
    title: "A Tender Feeling",
    source: "Sword Art Online",
    artist: "Yuki Kajiura",
    videoLink: "https://youtu.be/nts5ia-0O6c",
    genre: "Anime",
    tuning: {
      name: "Open B",
      strings: ["B", "F#", "B", "F#", "B", "D#"],
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "",
    },
    difficulty: 3,
  },
  {
    title: "Assassin's Creed III Main Theme",
    artist: "Lorne Balfe",
    videoLink: "https://youtu.be/nc6UOFO9ZZc",
    genre: "Game",
    tuning: {
      name: "Standard",
      strings: ["E", "A", "D", "G", "B", "E"],
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0239435",
    },
    difficulty: 2,
  },
  {
    title: "Here With You",
    source: "Mirai Nikki",
    artist: "Tatsuya Kato",
    videoLink: "https://youtu.be/8_2_JyIT5JI",
    genre: "Anime",
    tuning: {
      name: "Raise F",
      strings: ["F", "A", "D", "G", "B", "E"],
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0237446",
    },
    difficulty: 3,
  },
  {
    title:
      "Faded, This Is What You Came, Closer, Adventure of a Lifetime, The Greatest, Cheap Thrills, Treat you Better, Say You Won’t Let Go, Love Yourself, One Call Away, Hymn for the Weekend, Dangerously, 7 Years, Pillow Talk, In the Name of Love",
    source: "2016 Medley",
    artist:
      "Alan Walker, Calvin Harris, The Chainsmokers, Coldplay, Sia, Shawn Mendes, James Arthur, Justin Bieber, Charlie Puth, Lukas Graham, Zayn, Martin Garrix",
    videoLink: "https://youtu.be/G_F4iG5_l0s",
    genre: "Medley",
    tuning: {
      name: "Standard",
      strings: ["E", "A", "D", "G", "B", "E"],
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0236925",
    },
    difficulty: 7,
  },
  {
    title:
      "Attention, Feels, How Long, Dusk Till Dawn, MAsk Off, Too Good at Goodbyes, Symphony, Love, Fake Happy, Shape of You, New Rules, Despacito, Believer, Fetish",
    source: "2017 Medley",
    artist:
      "Charlie Puth, Calvin Harris, Sia, Future, Sam Smith, Clean Bandit, Zara Larsson, Lana Del Ray, Paramore, Ed Sheeran, Dua Lipa, Luis FOnsi, Daddy Yankee, Imagine Dragons, Selena Gomez",
    videoLink: "https://youtu.be/PxirHW1sT3Y",
    genre: "Medley",
    tuning: {
      name: "Standard",
      strings: ["E", "A", "D", "G", "B", "E"],
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0235405",
    },
    difficulty: 6,
  },
  {
    title: "Redo",
    source: "Re:Zero − Starting Life in Another World",
    artist: "Konomi Suzuki",
    videoLink: "https://youtu.be/38PucI0CBZY",
    genre: "Anime",
    tuning: {
      name: "Open C",
      strings: ["C", "G", "C", "G", "C", "E"],
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0235334",
    },
    difficulty: 7,
  },
  {
    title: "The Rains of Castamere",
    source: "Game of Thrones",
    artist: "Ramin Djawadi",
    videoLink: "https://youtu.be/yDHm_yRcRHo",
    spotifyLink: "https://open.spotify.com/track/3QvYQljqqIgxWHgeqQX28I?si=72c5e2fdcc244330",
    genre: "TV/Movie",
    tuning: {
      name: "Open Cm",
      strings: ["C", "G", "C", "G", "C", "D#"],
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0235333",
    },
    difficulty: 4,
  },
  {
    title: "In the Name of Love",
    artist: "Martin Garrix & Bebe Rexha",
    videoLink: "https://youtu.be/p8JlolXJC0k",
    spotifyLink: "https://open.spotify.com/track/5Byx7WPth2xwHpkQQf1cwy?si=a8011fe2d2b446a3",
    genre: "EDM",
    tuning: {
      name: "Open Cadd9",
      strings: ["C", "G", "C", "E", "G", "D"],
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0235224",
    },
    difficulty: 6,
  },
  {
    title: "Jiyuu no Tsubasa",
    source: "Attack on Titan",
    artist: "Linked Horizon",
    videoLink: "https://youtu.be/q6I1CI77cyE",
    spotifyLink: "https://open.spotify.com/track/3uIXlfdRCvKA0NfEX2nvjR?si=f0d3b9caab8b4c1f",
    genre: "Anime",
    tuning: {
      name: "Standard",
      strings: ["E", "A", "D", "G", "B", "E"],
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0234801",
    },
    difficulty: 7,
  },
  {
    title: "For the Damaged Coda",
    artist: "Blonde Redhead",
    videoLink: "https://youtu.be/SIvS0LCWbpw",
    genre: "Alternative",
    tuning: {
      name: "Open Bsus4",
      strings: ["B", "F#", "B", "F#", "B", "E"],
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0234800",
    },
    difficulty: 5,
  },
  {
    title: "Clocks",
    artist: "Coldplay",
    videoLink: "https://youtu.be/-W2vDAmXDQY",
    genre: "Alternative",
    tuning: {
      name: "Drop D",
      strings: ["D", "A", "D", "G", "B", "E"],
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0234798",
    },
    difficulty: 4,
  },
  {
    title: "Guren no Yumiya",
    source: "Attack on Titan",
    artist: "Linked Horizon",
    videoLink: "https://youtu.be/YItwILZbLkA",
    genre: "Anime",
    tuning: {
      name: "Open Gm",
      strings: ["D", "G", "D", "G", "A#", "D"],
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0234602",
    },
    difficulty: 4,
  },
  {
    title: "Warriors",
    source: "League of Legends",
    artist: "Imagine Dragons",
    videoLink: "https://youtu.be/PcpTkUAuyiE",
    genre: "Game",
    tuning: {
      name: "Open Fm",
      strings: ["C", "F", "C", "F", "G#", "C"],
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0191852",
    },
    difficulty: 5,
  },
  {
    title: "Roundabout",
    source: "Jojo's Bizarre Adventure",
    artist: "Yes",
    videoLink: "",
    spotifyLink: "https://open.spotify.com/track/7grLkzTJZRG6o9cbZFZxW8?si=50a56688dc374658",
    genre: "Anime",
    tuning: {
      name: "Standard",
      // TODO: This won't work for duets. Change it to type string.
      strings: ["E", "A", "D", "G", "B", "E"],
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "",
    },
    difficulty: 6,
  },
  // {
  //   title: "",
  //   source: "",
  //   artist: "",
  //   videoLink: "",
  //   spotifyLink: "",
  //   genre: "",
  //   tuning: {
  //     name: "Open ",
  //     strings: ["", "", "", "", "", ""],
  //   },
  //   button: {
  //     type: "buy",
  //     price: 7.99,
  //     link: "",
  //   },
  //   difficulty: 0,
  // },
];
