import { TabInfo } from "../types/tabs";

// https://gdex.cc/?_14.16.15.18.17.22.6.7.11.1.2.3.4.5.19.28.24.23.29
export const tabs: TabInfo[] = [
  {
    title: "Free",
    source: "Free! [OST]",
    artist: "Free",
    isAnime: false,
    youtube: "https://youtu.be/wQANVR4vqXI",
    tuning: {
      name: "Open D#maj7",
      strings: "D# G D G A# D",
    },
    button: {
      type: "free",
      link: "https://google.com",
    },
    difficulty: 0,
  },
  {
    title: "Suzume",
    source: "Suzume no Tojimari [OST]",
    artist: "RADWIMPS",
    isAnime: true,
    youtube: "https://youtu.be/wQANVR4vqXI",
    tuning: {
      name: "Open D#maj7",
      strings: "D# G D G A# D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0268543",
    },
    guitardex: "https://gdex.cc/?Suzume_4.1.2.14.18.24.23.15",
    difficulty: 5,
  },
  {
    title: "I Really Want to Stay At Your House",
    source: "Cyberpunk: Edgerunners [OST]",
    artist: "Rosa Walton, Hallie Coggins",
    youtube: "https://youtu.be/DGtyrC2Xn3g",
    isAnime: true,
    tuning: {
      name: "Open A#maj7",
      strings: "A# F D F A F",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0268403",
    },
    guitardex: "https://gdex.cc/?IRWTSAYH_14.24.1.2.22.17",
    difficulty: 5,
  },
  // {
  //   title: "Krone",
  //   source: "Guilty Crown [OST]",
  //   artist: "Hiroyuki Sawano",
  //   youtube: "https://youtu.be/9JOwtlOqXIA",
  //   isAnime: true,
  //   guitardex: "",
  // difficulty: 0,
  // },
  // {
  //   title: "Die For You",
  //   artist: "Joji",
  //   youtube: "https://youtu.be/c-LBF9aST7Q",
  //   isAnime: false,
  //   guitardex: "",
  // difficulty: 0,
  // },
  // {
  //   title: "Anti-Hero",
  //   artist: "Taylor Swift",
  //   youtube: "",
  //   isAnime: false,
  //   guitardex: "",
  // difficulty: 0,
  // },
  // {
  //   title: "Glimpse of Us",
  //   artist: "Joji",
  //   youtube: "https://youtu.be/mgxGC2GP3Do",
  //   isAnime: false,
  //   guitardex: "",
  // difficulty: 0,
  // },
  // {
  //   title: "Shiver",
  //   source: "Mushishi Zoku Shou [OP]",
  //   artist: "Lucy Rose",
  //   youtube: "https://youtu.be/0qIkm6BOPCY",
  //   isAnime: true,
  //   guitardex: "",
  // difficulty: 0,
  // },
  // {
  //   title: "Bella Ciao",
  //   source: "La casa de papel (Money Heist)",
  //   artist: "Manu Pilas",
  //   youtube: "https://youtu.be/umVfZVUFt_k",
  //   isAnime: false,
  //   guitardex: "",
  // difficulty: 0,
  // },
  {
    title: "Make You Feel My Love",
    artist: "Bob Dylan",
    youtube: "https://youtu.be/sThWUbjevjE",
    isAnime: false,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0254688",
    },
    guitardex: "https://gdex.cc/?Make-You-Feel-My-Love_14.16.17",
    difficulty: 4,
  },
  {
    title: "The Rumbling",
    source: "Attack on Titan: Final Season Part 2 [OP]",
    artist: "SiM",
    youtube: "https://youtu.be/6Obd-qh9LJU",
    isAnime: true,
    tuning: {
      name: "Open G/D#",
      strings: "D# G D G B D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0253775",
    },
    guitardex: "https://gdex.cc/?The-Rumbling_4.5.1.2.6.24.16.18",
    difficulty: 6,
  },
  {
    title: "Enemy",
    source: "League of Legends - Arcane",
    artist: "Imagine Dragons",
    youtube: "https://youtu.be/_ZG7Q5SgD9s",
    isAnime: false,
    tuning: {
      name: "Open G/D#",
      strings: "D# G D G B D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0253634",
    },
    guitardex: "https://gdex.cc/?Enemy_14.17.18.4.5.19.1.2.28.23.6.7",
    difficulty: 6,
  },
  {
    title: "Red Light, Green Light, Way Back Then, I Remember My Name, Unfolded",
    source: "Squid Game Medley",
    artist: "Jung Jae-il",
    youtube: "https://youtu.be/LYcM1QIxmLA",
    isAnime: false,
    tuning: {
      name: "Open Cm",
      strings: "C G C G C D#",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0243443",
    },
    guitardex: "https://gdex.cc/?Squid-Game-Medley_7.15.17.16.4.5",
    difficulty: 4,
  },
  {
    title:
      "Hello, Good for You, Love Me Like You Do, Flashlight, Lean On, Waiting for Love, See You Again, Take Me to Church, Drag Me Down, Thinking Out Loud",
    source: "2015 Medley",
    artist:
      "Adele, Selena Gomez, Ellie Goulding, Jessie J, Major Lazer, Avicii, Wiz Khalifa, Hozier, One Direction, Ed Sheeran",
    youtube: "https://youtu.be/T5trmYRacAE",
    isAnime: false,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0243661",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "A Tender Feeling",
    source: "Sword Art Online [OST]",
    artist: "Yuki Kajiura",
    youtube: "https://youtu.be/nts5ia-0O6c",
    isAnime: true,
    tuning: {
      name: "Open B",
      strings: "B F# B F# B D#",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0243276",
    },
    guitardex: "",
    difficulty: 3,
  },
  {
    title: "Assassin's Creed III Main Theme",
    artist: "Lorne Balfe",
    youtube: "https://youtu.be/nc6UOFO9ZZc",
    isAnime: false,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0239435",
    },
    guitardex: "",
    difficulty: 2,
  },
  {
    title: "Here With You",
    source: "Mirai Nikki [OST]",
    artist: "Tatsuya Kato",
    youtube: "https://youtu.be/8_2_JyIT5JI",
    isAnime: true,
    tuning: {
      name: "Raise F",
      strings: "F A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0237446",
    },
    guitardex: "",
    difficulty: 4,
  },
  {
    title:
      "Faded, This Is What You Came, Closer, Adventure of a Lifetime, The Greatest, Cheap Thrills, Treat you Better, Say You Won’t Let Go, Love Yourself, One Call Away, Hymn for the Weekend, Dangerously, 7 Years, Pillow Talk, In the Name of Love",
    source: "2016 Medley",
    artist:
      "Alan Walker, Calvin Harris, The Chainsmokers, Coldplay, Sia, Shawn Mendes, James Arthur, Justin Bieber, Charlie Puth, Lukas Graham, Zayn, Martin Garrix",
    youtube: "https://youtu.be/G_F4iG5_l0s",
    isAnime: false,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0236925",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title:
      "Attention, Feels, How Long, Dusk Till Dawn, MAsk Off, Too Good at Goodbyes, Symphony, Love, Fake Happy, Shape of You, New Rules, Despacito, Believer, Fetish",
    source: "2017 Medley",
    artist:
      "Charlie Puth, Calvin Harris, Sia, Future, Sam Smith, Clean Bandit, Zara Larsson, Lana Del Ray, Paramore, Ed Sheeran, Dua Lipa, Luis FOnsi, Daddy Yankee, Imagine Dragons, Selena Gomez",
    youtube: "https://youtu.be/PxirHW1sT3Y",
    isAnime: false,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 5.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0235405",
    },
    guitardex: "",
    difficulty: 7,
  },
  {
    title: "Redo",
    source: "Re:Zero [OP]",
    artist: "Konomi Suzuki",
    youtube: "https://youtu.be/38PucI0CBZY",
    isAnime: true,
    tuning: {
      name: "Open C",
      strings: "C G C G C E",
    },
    button: {
      type: "buy",
      price: 5.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0235334",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "The Rains of Castamere",
    source: "Game of Thrones",
    artist: "Ramin Djawadi",
    youtube: "https://youtu.be/yDHm_yRcRHo",
    spotify: "https://open.spotify.com/track/3QvYQljqqIgxWHgeqQX28I",
    isAnime: false,
    tuning: {
      name: "Open Cm",
      strings: "C G C G C D#",
    },
    button: {
      type: "buy",
      price: 5.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0235333",
    },
    guitardex: "",
    difficulty: 4,
  },
  {
    title: "In the Name of Love",
    artist: "Martin Garrix & Bebe Rexha",
    youtube: "https://youtu.be/p8JlolXJC0k",
    spotify: "https://open.spotify.com/track/5Byx7WPth2xwHpkQQf1cwy",
    isAnime: false,
    tuning: {
      name: "Open Cadd9",
      strings: "C G C E G D",
    },
    button: {
      type: "buy",
      price: 5.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0235224",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "Jiyuu no Tsubasa",
    source: "Attack on Titan [OP2]",
    artist: "Linked Horizon",
    youtube: "https://youtu.be/q6I1CI77cyE",
    spotify: "https://open.spotify.com/track/3uIXlfdRCvKA0NfEX2nvjR",
    isAnime: true,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 5.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0234801",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "For the Damaged Coda",
    artist: "Blonde Redhead",
    youtube: "https://youtu.be/SIvS0LCWbpw",
    isAnime: false,
    tuning: {
      name: "Open Bsus4",
      strings: "B F# B F# B E",
    },
    button: {
      type: "buy",
      price: 5.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0234800",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Clocks",
    artist: "Coldplay",
    youtube: "https://youtu.be/-W2vDAmXDQY",
    isAnime: false,
    tuning: {
      name: "Drop D",
      strings: "D A D G B E",
    },
    button: {
      type: "buy",
      price: 5.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0234798",
    },
    guitardex: "",
    difficulty: 3,
  },
  {
    title: "Guren no Yumiya",
    source: "Attack on Titan [OP]",
    artist: "Linked Horizon",
    youtube: "https://youtu.be/YItwILZbLkA",
    isAnime: true,
    tuning: {
      name: "Open Gm",
      strings: "D G D G A# D",
    },
    button: {
      type: "buy",
      price: 5.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0234602",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "Warriors",
    source: "League of Legends",
    artist: "Imagine Dragons",
    youtube: "https://youtu.be/PcpTkUAuyiE",
    isAnime: false,
    tuning: {
      name: "Open Fm",
      strings: "C F C F G# C",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0191852",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Roundabout",
    source: "Jojo's Bizarre Adventure [ED]",
    artist: "Yes",
    spotify: "https://open.spotify.com/track/7grLkzTJZRG6o9cbZFZxW8",
    isAnime: true,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 5.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0234601",
    },
    guitardex: "",
    difficulty: 7,
  },
  {
    title: "Blood Circulator",
    source: "Naruto: Shippuden [OP19]",
    artist: "Asian Kung-Fu Generation",
    youtube: "https://youtu.be/iEh8frYAkjw",
    spotify: "https://open.spotify.com/track/2VrKOurPkPNS5ajibJ9AFC",
    isAnime: true,
    tuning: {
      name: "Open D#maj7",
      strings: "D# G D G A# D",
    },
    button: {
      type: "buy",
      price: 5.99,
      link: "http://localhost:3001/tabs",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "Young",
    artist: "The Chainsmokers",
    youtube: "https://youtu.be/2v_WZfAR-sg",
    spotify: "https://open.spotify.com/track/7FZCEFCzeQ0pPXCq9I6bpa",
    isAnime: false,
    tuning: {
      name: "Open A#maj9",
      strings: "A# F# D# F# A# C#",
    },
    button: {
      type: "buy",
      price: 5.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0234509",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "History Maker",
    source: "Yuri!!! on Ice [OP]",
    artist: "Dean Fujioka",
    youtube: "https://youtu.be/is_hB23MnsY",
    spotify: "https://open.spotify.com/track/7LFnWlU8XqsqgKTNxtCEMX",
    isAnime: true,
    tuning: {
      name: "Open Csus2",
      strings: "C G C G C D",
    },
    button: {
      type: "buy",
      price: 5.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0234492",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Otherside",
    artist: "Red Hot Chili Peppers",
    youtube: "https://youtu.be/NHuLpjyZPPs",
    isAnime: false,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 5.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0234493",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Shiruishi",
    source: "Sword Art Online II [ED]",
    artist: "LiSA",
    youtube: "https://youtu.be/dc5zGlAQHjY",
    isAnime: true,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0234491",
    },
    guitardex: "",
    difficulty: 4,
  },
  {
    title: "I Don't Wanna Live Forever",
    source: "Fifty Shades Darker",
    artist: "Taylor Swift, Jack Antonoff, Sam Dew",
    youtube: "https://youtu.be/iN1NSHVDZXE",
    spotify: "https://open.spotify.com/track/6w3LCVradKDVgpWvpGZEol",
    isAnime: false,
    tuning: {
      name: "Open D#maj7",
      strings: "D# G D G A# D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0234490",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Westworld Theme",
    artist: "Ramin Djawadi",
    youtube: "https://youtu.be/eKslQCItZjI",
    spotify: "https://open.spotify.com/track/3v8eOj39dwOu1SSq5YFGD6",
    isAnime: false,
    tuning: {
      name: "Raise F",
      strings: "F A D G B E",
    },
    button: {
      type: "buy",
      price: 5.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0234510",
    },
    guitardex: "",
    difficulty: 4,
  },
  {
    title: "Hedwig's Theme",
    source: "Harry Potter",
    artist: "John Williams",
    youtube: "https://youtu.be/9bEbuj4Qb3I",
    isAnime: false,
    tuning: {
      name: "D#maj7",
      strings: "D# G D G A# D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0234507",
    },
    guitardex: "",
    difficulty: 1,
  },
  {
    title: "Flashlight",
    artist: "Jessie J",
    youtube: "https://youtu.be/MVZLT6QKGCY",
    spotify: "https://open.spotify.com/track/0ejG4fIbfnL0ThIJZPT4nG",
    isAnime: false,
    tuning: {
      name: "Open C",
      strings: "C G C G C E",
    },
    button: {
      type: "buy",
      price: 4.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0225313",
    },
    guitardex: "",
    difficulty: 4,
  },
  {
    title: "Scared to be Lonely",
    artist: "Martin Garrix & Dua Lipa",
    youtube: "https://youtu.be/xMnMdwJx9n8",
    spotify: "https://open.spotify.com/track/0fmWnDXzwc2UfV43OS4gxy",
    isAnime: false,
    tuning: {
      name: "D#maj7",
      strings: "D# G D G A# D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0225303",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Fix You",
    artist: "Coldplay",
    youtube: "https://youtu.be/fuNheENbBgs",
    spotify: "https://open.spotify.com/track/0jcwIVkZe9S2XnTV2t4sDV",
    isAnime: false,
    tuning: {
      name: "Open C5",
      strings: "C G C G G C",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0225224",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Euterpe (Inori's Song)",
    source: "Guilty Crown [OST]",
    artist: "Ryo (Supercell)",
    youtube: "https://youtu.be/mMTTDKye_44",
    spotify: "https://open.spotify.com/track/7tSSsPUahcEHCMvmXySbLw",
    isAnime: true,
    tuning: {
      name: "Open Csus4",
      strings: "C G C G C F",
    },
    button: {
      type: "buy",
      price: 4.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0225218",
    },
    guitardex: "",
    difficulty: 3,
  },
  {
    title: "Isabella's Lullaby",
    source: "The Promised Neverland [OST]",
    artist: "Takahiro Obata",
    youtube: "https://youtu.be/zc-zOZ-gBR8",
    spotify: "https://open.spotify.com/track/5cBG7Xi3DgBfBwEbNhiszl",
    isAnime: true,
    tuning: {
      name: "Open Gsus2/C",
      strings: "C G C G A D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0218978",
    },
    guitardex: "",
    difficulty: 7,
  },
  {
    title: "Fly Me To The Moon",
    artist: "Frank Sinatra",
    youtube: "https://youtu.be/zO4s6-2loqQ",
    isAnime: false,
    tuning: {
      name: "Open Am7/C",
      strings: "C G C G A C",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0218564",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "Bravely You",
    source: "Charlotte [OP]",
    artist: "Jun Maeda",
    youtube: "https://youtu.be/hEkbkcu1fQs",
    spotify: "https://open.spotify.com/track/1MXANs2TnbG03wC2sIjM31",
    isAnime: true,
    tuning: {
      name: "Open G6/D#",
      strings: "D# G D G B E",
    },
    button: {
      type: "buy",
      price: 4.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0219418",
    },
    guitardex: "",
    difficulty: 4,
  },
  {
    title: "Hymn for the Weekend",
    artist: "Coldplay",
    youtube: "https://youtu.be/48R6TGsZ8e8",
    spotify: "https://open.spotify.com/track/4vYmXoZiDVxnqcXr55dh0o",
    isAnime: false,
    tuning: {
      name: "Open G#6",
      strings: "G# F C D# C D#",
    },
    button: {
      type: "buy",
      price: 4.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0218661",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "I Say Yes (Wedding Version)",
    source: "Zero no Tsukaima [OP2]",
    artist: "Shinkichi Mitsumune",
    youtube: "https://youtu.be/xcwSIEO4xkU",
    isAnime: true,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0218611",
    },
    guitardex: "",
    difficulty: 3,
  },
  {
    title: "Deal with the Devil",
    source: "Kakegurui [OP]",
    artist: "Ryo Yokota",
    youtube: "https://youtu.be/u2apIzst4bM",
    spotify: "https://open.spotify.com/track/1gAldEZGL44HZAX2sH43L3",
    isAnime: true,
    tuning: {
      name: "Open Gm",
      strings: "D G D G A# D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0218610",
    },
    guitardex: "",
    difficulty: 8,
  },
  {
    title: "Senbonzakura",
    artist: "WhiteFlame (Kurousa-P), Hatsune Miku",
    youtube: "https://youtu.be/6vex86Iq6Oo",
    spotify: "https://open.spotify.com/track/7uFr2YBn3HWk73jyLlKqEJ",
    isAnime: true,
    tuning: {
      name: "Open D#maj9",
      strings: "D# G D F A# D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0218348",
    },
    guitardex: "",
    difficulty: 7,
  },
  {
    title: "Realize",
    source: "Re:Zero Season 2 [OP]",
    artist: "Konomi Suzuki",
    youtube: "https://youtu.be/uiAlctriyWw",
    spotify: "https://open.spotify.com/track/3sju4Sv9qUIWOXToTPAeIu",
    isAnime: true,
    tuning: {
      name: "Open Cm",
      strings: "C G C G C D#",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0218137",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "Baka Mitai",
    source: "Yakuza 0",
    artist: "Ryosuke Horii, Mitsuharu Fukuyama",
    youtube: "https://youtu.be/1vZhC5kxQno",
    spotify: "https://open.spotify.com/album/0gkaFUGzdY1m11rtJCYXHz",
    isAnime: false,
    tuning: {
      name: "Open C",
      strings: "C G C G C E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0217543",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Red Swan",
    source: "Attack on Titan Season 3 [OP]",
    artist: "Hyde",
    youtube: "https://youtu.be/Kk76m67gux8",
    spotify: "https://open.spotify.com/track/6ePNDktLmJKpMGJx2SCIgE",
    isAnime: true,
    tuning: {
      name: "Open E",
      strings: "E G# B E B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0189131",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Deja Vu",
    source: "Initial D [OST]",
    artist: "Dave Rodgers",
    youtube: "https://youtu.be/YopskwDy45I",
    spotify: "https://open.spotify.com/track/1aSm0jHIJpglPZXh3yO0Py",
    isAnime: true,
    tuning: {
      name: "Standard\nOpen D",
      strings: "E A D G B E\nD A D F# A D",
    },
    button: {
      type: "buy",
      price: 8.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0217689",
    },
    guitardex: "",
    difficulty: 7,
  },
  {
    title: "Astronomia",
    source: "Coffin Dance",
    artist: "Tony Igy, Vicetone",
    youtube: "https://youtu.be/l0K53I7lFh0",
    isAnime: false,
    tuning: {
      name: "Open Cm",
      strings: "C G C G C D#",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0210840",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Snow (Hey Oh)",
    artist: "Red Hot Chili Peppers",
    youtube: "https://youtu.be/uSbsoyG4W2Q",
    spotify: "https://open.spotify.com/track/20kc6hE07GY8SIU1TYTYGm",
    isAnime: false,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0209515",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Heikosen",
    source: "Kuzu no Honkai [ED]",
    artist: "Sayuri",
    youtube: "https://youtu.be/A1BUuD1O5gI",
    spotify: "https://open.spotify.com/track/43hhgQnmsSMujLyqpJLvmI",
    isAnime: true,
    tuning: {
      name: "Drop D",
      strings: "D A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0209516",
    },
    guitardex: "",
    difficulty: 7,
  },
  {
    title: "Love Yourself",
    artist: "Justin Bieber, Ed Sheeran, Benny Blanco",
    youtube: "https://youtu.be/iyIhP5_JcOA",
    spotify: "https://open.spotify.com/track/49Hn5OZgDcZvkXjFV2jitt",
    isAnime: false,
    tuning: {
      name: "Open Csus2",
      strings: "C G C G C D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0209487",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Krone",
    source: "Guilty Crown [OST]",
    artist: "Hiroyuki Sawano",
    youtube: "https://youtu.be/9JOwtlOqXIA",
    spotify: "https://open.spotify.com/track/1cLwm9dinKGwMSVgrjtrsT",
    isAnime: true,
    tuning: {
      name: "Open D#maj7",
      strings: "D# G D G A# D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0209040",
    },
    guitardex: "",
    difficulty: 4,
  },
  {
    title: "Interstellar Main Theme",
    artist: "Hans Zimmer",
    youtube: "https://youtu.be/-dR5V0jskSs",
    spotify: "https://open.spotify.com/track/0WvNmvJSdBNoN089hQC871",
    isAnime: false,
    tuning: {
      name: "Open Dm(maj7)",
      strings: "D F A F A C#",
    },
    button: {
      type: "buy",
      price: 5.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0209039",
    },
    guitardex: "",
    difficulty: 2,
  },
  {
    title: "Gotta Catch 'Em All!",
    source: "Pokemon [OP]",
    artist: "Jason Paige, John Siegler, John Loeffler",
    youtube: "https://youtu.be/bPMYkuBrb5o",
    spotify: "https://open.spotify.com/track/74quNvLmMguXFx0uUM6HyZ",
    isAnime: true,
    tuning: {
      name: "1 Step Down",
      strings: "D G C F A D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0209038",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "We Are Number One",
    source: "Lazy Town",
    artist: "Máni Svavarsson, Stefán Karl Stefánsson",
    youtube: "https://youtu.be/RdS-zJjXeIk",
    isAnime: false,
    tuning: {
      name: "Open C#maj7",
      strings: "C# F C F G# C",
    },
    button: {
      type: "buy",
      price: 4.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0209013",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Sad Theme",
    source: "One Punch Man [OST]",
    artist: "Makoto Miyazaki",
    youtube: "https://youtu.be/LnoXxqILT7Y",
    spotify: "https://open.spotify.com/track/3CqV5uSdPvj5Ux3E8Idusc",
    isAnime: true,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0209011",
    },
    guitardex: "",
    difficulty: 4,
  },
  {
    title: "Starboy",
    artist: "The Weeknd, Daft Punk",
    youtube: "https://youtu.be/jG1lbuvKVM0",
    spotify: "https://open.spotify.com/track/5ZlAq2Z7GglWqlr1j8I4eB",
    isAnime: false,
    tuning: {
      name: "Open D#maj7",
      strings: "D# G D G A# D",
    },
    button: {
      type: "buy",
      price: 4.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0209012",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "THE DAY",
    source: "Boku no Hero Academia [OP]",
    artist: "Porno Graffitti",
    youtube: "https://youtu.be/6kGAx70Coo0",
    spotify: "https://open.spotify.com/track/1Kwrq3whtnoVQLXG24HL9q",
    isAnime: true,
    tuning: {
      name: "Open Cm",
      strings: "C G C G C D#",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0208845",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "Davy Jones",
    source: "Pirates of the Caribbean",
    artist: "Hans Zimmer",
    youtube: "https://youtu.be/1jLh28fY4QA",
    spotify: "https://open.spotify.com/track/74r3tHLUWNS5ZFoUS8p6XU",
    isAnime: false,
    tuning: {
      name: "Open Gm/C",
      strings: "C G D G A# D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0208732",
    },
    guitardex: "",
    difficulty: 2,
  },
  {
    title: "Run",
    artist: "Joji",
    youtube: "https://youtu.be/nV9o1_Mc-NU",
    isAnime: false,
    tuning: {
      name: "Open Cm\nStandard",
      strings: "C G D# G C D#\nE A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0208681",
    },
    guitardex: "",
    difficulty: 6, // Maybe 7
  },
  {
    title: "Closed on Sunday",
    artist: "Kanye West",
    youtube: "https://youtu.be/3j3qszALnE8",
    isAnime: false,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0205852",
    },
    guitardex: "",
    difficulty: 4,
  },
  {
    title: "Gurenge",
    source: "Demon Slayer [OP]",
    artist: "LiSA",
    youtube: "https://youtu.be/TpobQaJtp0o",
    spotify: "https://open.spotify.com/track/58u0TB73Qb3mg6wGZsm5h8",
    isAnime: true,
    tuning: {
      name: "Open B",
      strings: "B F# B F# B D#",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0205693",
    },
    guitardex: "",
    difficulty: 7, // Maybe 6
  },
  {
    title: "Internet",
    artist: "Post Malone",
    youtube: "https://youtu.be/joODxDIzKO0",
    isAnime: false,
    tuning: {
      name: "Open Dsus4/B",
      strings: "B G D G A D",
    },
    button: {
      type: "buy",
      price: 4.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0218612",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Inferno",
    source: "Fire Force [OP]",
    artist: "Mrs.GREEN APPLE",
    youtube: "https://youtu.be/kKXizebFUhg",
    spotify: "https://open.spotify.com/track/3u5O7AjlwxElJPIEap8Iaf",
    isAnime: true,
    tuning: {
      name: "Open Cm",
      strings: "C G C G C D#",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0205715",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "bury a friend",
    artist: "Billie Eilish",
    youtube: "https://youtu.be/hnPnEJcaF7Q",
    spotify: "https://open.spotify.com/track/5UU1SFmkmIj0LtD3mamnKv",
    isAnime: false,
    tuning: {
      name: "Open Gm",
      strings: "D G D G A# D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0205851",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Torches",
    source: "Vinland Saga [ED]",
    artist: "Aimer",
    youtube: "https://youtu.be/33Bhmkz6JJA",
    spotify: "https://open.spotify.com/track/6ttWgxYEfyDzSackKha0KQ",
    isAnime: true,
    tuning: {
      name: "Open D#maj7",
      strings: "D# G D G A# D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0201073",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "Wet Hands, Sweden, Living Mice, Danny, Mice on Venus",
    source: "Minecraft Medley",
    artist: "Daniel Rosenfeld (C418)",
    youtube: "https://youtu.be/cXlhq0_ucmc",
    isAnime: false,
    tuning: {
      name: "Open Gsus2/C",
      strings: "C G D G A D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0200235",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Call of Silence",
    source: "Attack on Titan [OST]",
    artist: "Hiroyuki Sawano, Gemie",
    youtube: "https://youtu.be/ua6kPbGXcRc",
    spotify: "https://open.spotify.com/track/2HInaew8oU0F4dbgqm5jUl",
    isAnime: true,
    tuning: {
      name: "Open Dadd9",
      strings: "D A D F# A E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0205800",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Sanctuary",
    artist: "Joji",
    youtube: "https://youtu.be/m0iVo2E_mRQ",
    isAnime: false,
    tuning: {
      name: "Open G/C",
      strings: "C G C G B D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0218659",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "Kawaki wo Ameku",
    source: "Domestic na Kanojo [OP]",
    artist: "Minami",
    youtube: "https://youtu.be/QUO-F6z-ILk",
    spotify: "https://open.spotify.com/track/4dhT7zXf0SQX3weVKSbIAx",
    isAnime: true,
    tuning: {
      name: "Open Cm",
      strings: "C G C G C D#",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0199709",
    },
    guitardex: "",
    difficulty: 7,
  },
  {
    title: "Umi no Yuurei",
    source: "Children of the Sea [ED]",
    artist: "Kenshi Yonezu",
    youtube: "https://youtu.be/I29XpIFRblc",
    spotify: "https://open.spotify.com/track/7a2rh2MIRzMoT5prkZN08b",
    isAnime: true,
    tuning: {
      name: "Open G/C",
      strings: "C G C G B D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0198771",
    },
    guitardex: "",
    difficulty: 7,
  },
  {
    title: "EARFQUAKE",
    artist: "Tyler, the Creator",
    youtube: "https://youtu.be/GtjvG2ORzUY",
    spotify: "https://open.spotify.com/track/6ddsmQjfvckfyFcqCG0JqP",
    isAnime: false,
    tuning: {
      name: "Open B",
      strings: "B F# B F# B D#",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0200263",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "Renai Circulation",
    source: "Bakemonogatari [OP4]",
    artist: "Kana Hanazawa",
    youtube: "https://youtu.be/1MgIqz66NZA",
    spotify: "https://open.spotify.com/track/4NIQLdhKmhVnZWHJDtRirW",
    isAnime: true,
    tuning: {
      name: "Open C\nStandard",
      strings: "C G C G C E\nE A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0198298",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "Kaen",
    source: "Dororo [OP]",
    artist: "Queen Bee (Ziyoou-vachi)",
    youtube: "https://youtu.be/7RHFGzwEBv8",
    spotify: "https://open.spotify.com/track/4wZt3s82Y9OQ5LdUuY6aU9",
    isAnime: true,
    tuning: {
      name: "Open C",
      strings: "C G C G C E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0199040",
    },
    guitardex: "",
    difficulty: 6, // Maybe 7
  },
  {
    title: "bad guy",
    artist: "Billie Eilish",
    youtube: "https://youtu.be/pug5VSQHPgI",
    spotify: "https://open.spotify.com/track/3i2CsJu1qMCcI48Q5hSIVB",
    isAnime: false,
    tuning: {
      name: "Open Gm",
      strings: "D G D G A# D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0197812",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "I Don't Care",
    artist: "Ed Sheeran, Justin Bieber",
    youtube: "https://youtu.be/C1azs50n5r0",
    spotify: "https://open.spotify.com/track/09hvugZy2uvhlHsADVW14M",
    isAnime: false,
    tuning: {
      name: "Open D",
      strings: "D A D F# A D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0198256",
    },
    guitardex: "",
    difficulty: 7,
  },
  {
    title: "Old Town Road",
    artist: "Lil Nas X",
    youtube: "https://youtu.be/7RUuMwUtljI",
    spotify: "https://open.spotify.com/track/1shuiXJHe4BFbcgqnx8ZLc",
    isAnime: false,
    tuning: {
      name: "Open Cmaj7",
      strings: "C G C G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0198257",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "The Hero!!",
    source: "One Punch Man [OP]",
    artist: "JAM Project",
    youtube: "https://youtu.be/KWbGhwCnMx4",
    spotify: "https://open.spotify.com/track/3GSwDRLP7iKBOhQOzIYdZD",
    isAnime: true,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0196104",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Light of the Seven",
    source: "Game of Thrones",
    artist: "Ramin Djawadi",
    youtube: "https://youtu.be/6556AH1cBzw",
    spotify: "https://open.spotify.com/track/4Fv2DLddyAFqBPJZ0AkBEM",
    isAnime: false,
    tuning: {
      name: "Open Cm",
      strings: "C G D# G C D#",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0196103",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "Game of Thrones Theme",
    artist: "Ramin Djawadi",
    youtube: "https://youtu.be/lQ_92dXkcwc",
    spotify: "https://open.spotify.com/track/2zhe605XJwwGRgET8LXx9f",
    isAnime: false,
    tuning: {
      name: "Drop C",
      strings: "C G C F A D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0196102",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "Castle on the Hill",
    artist: "Ed Sheeran",
    youtube: "https://youtu.be/tjStH5qBnqY",
    spotify: "https://open.spotify.com/track/3OFPdxOBVtNZiWIbZIw2jv",
    isAnime: false,
    tuning: {
      name: "Open C",
      strings: "C G C G C E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0194278",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "Deep in Abyss",
    source: "Made in Abyss [OP]",
    artist: "Miyu Tomita, Mariya Ise",
    youtube: "https://youtu.be/A9cec7LuExo",
    spotify: "https://open.spotify.com/track/5tpJtPlcWjtzm9hUGOtGXa",
    isAnime: true,
    tuning: {
      name: "Open D/C#",
      strings: "D F# C# F# A C#",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0193718",
    },
    guitardex: "",
    difficulty: 7,
  },
  {
    title: "The Dragonborn Comes",
    source: "The Elder Scrolls: Skyrim",
    artist: "Jeremy Soule",
    youtube: "https://youtu.be/S7NBS5Wy-uM",
    spotify: "https://open.spotify.com/track/4efSWGSQ5pTWD6dr5BbmGz",
    isAnime: false,
    tuning: {
      name: "Open Cm",
      strings: "C G C G C D#",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0193704",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "It's My Life",
    artist: "Bon Jovi",
    youtube: "https://youtu.be/23KPYWT9tc0",
    spotify: "https://open.spotify.com/track/4vHR3YbSsnMJ6PQ8zDvTp8",
    isAnime: false,
    tuning: {
      name: "Open D#maj7",
      strings: "D# G D G A# D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0193394",
    },
    guitardex: "",
    difficulty: 4,
  },
  {
    title: "Swan Song",
    source: "Alita: Battle Angel",
    artist: "Dua Lipa",
    youtube: "https://youtu.be/6ddAnYbhpL4",
    spotify: "https://open.spotify.com/track/0ven9BR6gW06MFbllY8Muu",
    isAnime: false,
    tuning: {
      name: "Open G#6",
      strings: "G# D# C D# C F",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0193378",
    },
    guitardex: "",
    difficulty: 7,
  },
  {
    title: "Crab Rave",
    artist: "Noisestorm",
    youtube: "https://youtu.be/j8VdOwlgwPI",
    isAnime: false,
    tuning: {
      name: "Drop C",
      strings: "C G C F A D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0193136",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "idontwannabeyouanymore",
    artist: "Billie Eilish",
    youtube: "https://youtu.be/utce31tsEj8",
    spotify: "https://open.spotify.com/track/4G8IJDJqiUdA5e9sqt4MfY",
    isAnime: false,
    tuning: {
      name: "Open C",
      strings: "C G C G C E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0193054",
    },
    guitardex: "",
    difficulty: 7,
  },
  {
    title: "LIT",
    source: "Koe no Katachi [OST]",
    artist: "Kensuke Oshio",
    youtube: "https://youtu.be/A7GL8UvIWs0",
    spotify: "https://open.spotify.com/track/4NTCnxf11nUeDEJuDqDmJd",
    isAnime: true,
    tuning: {
      name: "Open B",
      strings: "B F# B F# B D#",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0191849",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "shadowgraph",
    source: "Boogiepop wa Warawanai [OP]",
    artist: "MYTH & ROID",
    youtube: "https://youtu.be/S5QEUCMqVEo",
    spotify: "https://open.spotify.com/track/1PNknkfeQ9CRlxIgeYd5fF",
    isAnime: true,
    tuning: {
      name: "Open A#",
      strings: "A# F C# F A# F",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0191670",
    },
    guitardex: "",
    difficulty: 10,
  },
  {
    title: "Secret Base",
    source: "Anohana [ED]",
    artist: "Zone",
    youtube: "https://youtu.be/gwr2_a3zX2g",
    spotify: "https://open.spotify.com/track/4qyJf5WfPTj4JxL6vmpsfB",
    isAnime: true,
    tuning: {
      name: "1/2 Step Down",
      strings: "D# G# C# F# A# D#",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0191670",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Crybaby",
    source: "Devilman Crybaby [OST]",
    artist: "Kensuke Ushio",
    youtube: "https://youtu.be/-3k8R2P_Z4c",
    spotify: "https://open.spotify.com/track/0V2bH7stS8o73GDMZclO6d",
    isAnime: true,
    tuning: {
      name: "Open Bm",
      strings: "B F# B F# B D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0192543",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "Azalea",
    source: "Citrus [OP]",
    artist: "nano.RIPE",
    youtube: "https://youtu.be/XxI6H39LM3I",
    spotify: "https://open.spotify.com/track/5yPZPSzGVo301By178Z969",
    isAnime: true,
    tuning: {
      name: "Open Cm",
      strings: "C G C G C D#",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0191924",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "Wet Hands",
    source: "Minecraft",
    artist: "Daniel Rosenfeld (C418)",
    youtube: "https://youtu.be/BvJ2YsWPckk",
    isAnime: false,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 5.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0192123",
    },
    guitardex: "",
    difficulty: 1,
  },
  {
    title: "Supermarket Flowers",
    artist: "Ed Sheeran",
    youtube: "https://youtu.be/j-6ormqziaI",
    spotify: "https://open.spotify.com/track/67mjHvHDZ44lCLBRZFfluE",
    isAnime: false,
    tuning: {
      name: "Open C",
      strings: "C G C G C E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0192088",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Apologize",
    artist: "Timbaland, One Republic",
    youtube: "https://youtu.be/AVE59W1kjZ0",
    spotify: "https://open.spotify.com/track/3yOiCx9ZiaHOse6uQDGpxo",
    isAnime: false,
    tuning: {
      name: "Open A#maj9",
      strings: "A# F D F A C",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0191923",
    },
    guitardex: "",
    difficulty: 7,
  },
  {
    title: "Ref:rain",
    source: "Koi wa Ameagari no You ni [ED]",
    artist: "Aimer",
    youtube: "https://youtu.be/FkbIDH26HNo",
    isAnime: true,
    tuning: {
      name: "Open Cm",
      strings: "C G D# G C D#",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0191856",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "New Rules",
    artist: "Dua Lipa",
    youtube: "https://youtu.be/cSwCc2VpS7k",
    spotify: "https://open.spotify.com/track/1lA2bdxSA9i0XfeVnu4F7o",
    isAnime: false,
    tuning: {
      name: "Open D#maj7",
      strings: "D# G D G A# D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0192138",
    },
    guitardex: "",
    difficulty: 7,
  },
  // TODO: Removed from MN
  // {
  //   title: "Kyouran Hey Kids!!",
  //   source: "Noragami Aragoto [OP]",
  //   artist: "THE ORAL CIGARETTES",
  //   youtube: "https://youtu.be/I0-pVDOA4OE",
  //   spotify: "https://open.spotify.com/track/6VB22XW4UIQiJLiC9kAuoG",
  //   isAnime: true,
  //   tuning: {
  //     name: "Raise F",
  //     strings: "F A D G B E",
  //   },
  //   button: {
  //     type: "buy",
  //     price: 7.99,
  //     link: "https://www.musicnotes.com/sheetmusic/display_error.asp?ppn=MN0192097",
  //   },
  //   guitardex: "",
  // difficulty: 0,
  // },
  {
    title: "Ichiban no Takaramono",
    source: "Angel Beats! [OST]",
    artist: "Jun Maeda",
    youtube: "https://youtu.be/FzcdABw5s_c",
    spotify: "https://open.spotify.com/track/3HcgM4wC07xE2pjhK0dmsX",
    isAnime: true,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0191853",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Innocence",
    source: "Sword Art Online [OP2]",
    artist: "Eir Aoi",
    youtube: "https://youtu.be/-CV0Q0H2Qqo",
    spotify: "https://open.spotify.com/track/2GAIzk6TJhO8uNYej6s7ZV",
    isAnime: true,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0191968",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "See You Again",
    artist: "Wiz Khalifa, Charlie Puth",
    youtube: "https://youtu.be/OqXuyb3qSvw",
    isAnime: false,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0191851",
    },
    guitardex: "",
    difficulty: 4,
  },
  {
    title: "My Hero",
    source: "Inuyashiki [OP]",
    artist: "MAN WITH A MISSION",
    youtube: "https://youtu.be/Tml9tPCcCCA",
    spotify: "https://open.spotify.com/track/0FIC7v7EC0AnnKUCoFEy07",
    isAnime: true,
    tuning: {
      name: "Open Cm",
      strings: "C G C G C D#",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0191854",
    },
    guitardex: "",
    difficulty: 7,
  },
  {
    title:
      "FRIENDS, Rockstar, Wolves, One Kiss, Falling Down, Havana, no tears left to cry, Lucid Dreams, Mariners Apartment Complex, Lemon, when the party's over, Lovely, Jocelyn Flores, ALONE, PART 3",
    source: "2018 Medley",
    artist:
      "Anne-Marie, Marshmello, Post Malone, 21 Savage, Selena Gomez, Dua Lipa, Calvin Harris, XXXTENTACION, Lil Peep, Camila Cabello, Ariana Grande Juice Wrld, Lana del Rey, Kenshi Yonezu, Billie Eilish, Khalid",
    youtube: "https://youtu.be/swcdVwnERco",
    isAnime: false,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 9.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0191937",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "My Soul, Your Beats!",
    source: "Angel Beats [OP]",
    artist: "Jun Maeda, Lia",
    youtube: "https://youtu.be/iGQXJNu5UXc",
    spotify: "https://open.spotify.com/track/7MZLqteD1lSyffiRrLaHjQ",
    isAnime: true,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0191925",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Memoria",
    source: "Fate/Zero [ED]",
    artist: "Eir Aoi",
    youtube: "https://youtu.be/MlzL3tMKE70",
    spotify: "https://open.spotify.com/track/3Ptnox8TfCbkam9TYdLfj7",
    isAnime: true,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0191848",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "Brothers (Bratja)",
    source: "FullMetal Alchemist [OST]",
    artist: "Michiru Ooshima, Seiji Mizushima, Tatiana Naumova",
    youtube: "https://youtu.be/IVnegQXUr3U",
    isAnime: true,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0191850",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Let Me Hear",
    source: "Parasyte [OP]",
    artist: "Fear, and Loathing in Las Vegas",
    youtube: "https://youtu.be/BKxq6ftfVSA",
    spotify: "https://open.spotify.com/track/7vR5BCpsFWpxPbf0H1STZu",
    isAnime: true,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0191969",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "Photograph",
    artist: "Ed Sheeran",
    youtube: "https://youtu.be/sXUJtMEKHQY",
    isAnime: false,
    tuning: {
      name: "Open A",
      strings: "A E C# E A E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0191697",
    },
    guitardex: "",
    difficulty: 4,
  },
  {
    title: "The Scientist",
    artist: "Coldplay",
    youtube: "https://youtu.be/tKwuKftVUI8",
    spotify: "https://open.spotify.com/track/3HVCB7SiyrHoAPNtDdqZA3",
    isAnime: false,
    tuning: {
      name: "Open A#",
      strings: "A# F A# F A# D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0191855",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "Snow Fairy",
    source: "Fairy Tail [OP]",
    artist: "Funkist",
    youtube: "https://youtu.be/Z6Z8V_M2hWc",
    spotify: "https://open.spotify.com/track/1Rl1EbV0e7GwroKpwSipX2",
    isAnime: true,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0191671",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "All of Me",
    artist: "John Legend",
    youtube: "https://youtu.be/1eaOdePV2Tc",
    spotify: "https://open.spotify.com/track/6jk4LFgTJmzpsr0wD8bmh4",
    isAnime: false,
    tuning: {
      name: "Open A#maj9",
      strings: "A# F D F A C",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0191627",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Crossing Field",
    source: "Sword Art Online [OP]",
    artist: "LiSA",
    youtube: "https://youtu.be/1hTiGdOp9Bk",
    spotify: "https://open.spotify.com/track/6st3fVuEPbwKCc4e4xkJXt",
    isAnime: true,
    tuning: {
      name: "Raise F",
      strings: "F A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0191628",
    },
    guitardex: "",
    difficulty: 4,
  },
  {
    title: "A Cruel Angel's Thesis",
    source: "Neon Genesis Evangelion [OP]",
    artist: "Yoko Takahashi",
    youtube: "https://youtu.be/4JKP013TOIQ",
    spotify: "https://open.spotify.com/track/0V0gY9dRpt2ZpGw9X6mpge",
    isAnime: true,
    tuning: {
      name: "Raise F",
      strings: "F A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0191696",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "Fairy Tail Main Theme",
    source: "Fairy Tail [OST]",
    artist: "Yasuharu Takanashi",
    youtube: "https://youtu.be/Bgwvvu6Z8xs",
    spotify: "https://open.spotify.com/track/4Dmdxf6W2uZquwF8TgvhHu",
    isAnime: true,
    tuning: {
      name: "1/2 Step Down",
      strings: "D# G# C# F# A# D#",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0191656",
    },
    guitardex: "",
    difficulty: 4,
  },
  {
    title: "Hey Brother",
    artist: "Avicii",
    youtube: "https://youtu.be/xbeLoC9MsO4",
    isAnime: false,
    tuning: {
      name: "Open C7sus2/D",
      strings: "D G D G A# C",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0191655",
    },
    guitardex: "",
    difficulty: 4,
  },
  {
    title: "Courage",
    source: "Sword Art Online II [OP2]",
    artist: "Haruka Tomatsu",
    youtube: "https://youtu.be/eXB1DBRSvNQ",
    spotify: "https://open.spotify.com/track/7h8CCKCyi2ynIitjj0PKwW",
    isAnime: true,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0191738",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "Ignite",
    source: "Sword Art Online II [OP]",
    artist: "Eir Aoi",
    youtube: "https://youtu.be/i7IOR8FDc5M",
    spotify: "https://open.spotify.com/track/5Eawg1Z9HxPkEUAdy1Im6W",
    isAnime: true,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0191669",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Radioactive",
    artist: "Imagine Dragons",
    youtube: "https://youtu.be/OL_3h3hP-LA",
    isAnime: false,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0191654",
    },
    guitardex: "",
    difficulty: 4,
  },
  {
    title: "Demons",
    artist: "Imagine Dragons",
    youtube: "https://youtu.be/Aci2ZgyFUm8",
    spotify: "https://open.spotify.com/track/1hoUhg0a4jgMSVISelNaAN",
    isAnime: false,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0191629",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Flamingo",
    artist: "Kenshi Yonezu",
    youtube: "https://youtu.be/yrs_zWcdxHE",
    spotify: "https://open.spotify.com/track/23WHZJj7UETlnaicfPxo1S",
    isAnime: false,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0191563",
    },
    guitardex: "",
    difficulty: 7,
  },
  {
    title: "BAD!",
    artist: "XXXTENTACION",
    youtube: "https://youtu.be/IV16BW5eJwQ",
    spotify: "https://open.spotify.com/track/1ol6nKyyJCwMUPBAYUBuVF",
    isAnime: false,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0191334",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "The Place Where Wishes Come True",
    source: "Clannad [OST]",
    artist: "Jun Maeda",
    youtube: "https://youtu.be/HLDVlzLWxN0?t=1070",
    spotify: "https://open.spotify.com/track/2jxcTMgp5RHTg2RhZcIr2Z",
    isAnime: true,
    tuning: {
      name: "Open C",
      strings: "C G C G C E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0191631",
    },
    guitardex: "",
    difficulty: 3,
  },
  {
    title: "Shining in the Sky",
    source: "Clannad [OST]",
    artist: "Magome Togoshi",
    youtube: "https://youtu.be/HLDVlzLWxN0?t=826",
    spotify: "https://open.spotify.com/track/1fhAHFNBxMY6M9po3t6EZj",
    isAnime: true,
    tuning: {
      name: "Open C",
      strings: "C G C G C E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0191630",
    },
    guitardex: "",
    difficulty: 4,
  },
  {
    title: "Spring Wind",
    source: "Clannad [OST]",
    artist: "Shinji Orito",
    youtube: "https://youtu.be/HLDVlzLWxN0?t=635",
    spotify: "https://open.spotify.com/track/3YmeEkyAgfokz6m1vKGm6j",
    isAnime: true,
    tuning: {
      name: "Open C",
      strings: "C G C G C E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0191566",
    },
    guitardex: "",
    difficulty: 4,
  },
  {
    title: "Roaring Tides",
    source: "Clannad [OST]",
    artist: "Shinji Orito",
    youtube: "https://youtu.be/HLDVlzLWxN0?t=464",
    spotify: "https://open.spotify.com/track/3048OYgfowde8pld2y0bTi",
    isAnime: true,
    tuning: {
      name: "Drop D",
      strings: "D A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0190983",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Toki Wo Kizamu Uta",
    source: "Clannad After Story [OP]",
    artist: "Jun Maeda, Lia",
    youtube: "https://youtu.be/HLDVlzLWxN0?t=227",
    spotify: "https://open.spotify.com/track/7a5A0DNRWl8YjoBmBOAw5c",
    isAnime: true,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0190820",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Dango Daikazoku",
    source: "Clannad [ED]",
    artist: "Jun Maeda",
    youtube: "https://youtu.be/HLDVlzLWxN0",
    spotify: "https://open.spotify.com/track/1eODf4PvA6xUCHiCdhc2uk",
    isAnime: true,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0190748",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "This Game",
    source: "No Game No Life [OP]",
    artist: "Konomi Suzuki",
    youtube: "https://youtu.be/1Oz5R6Rw2TY",
    spotify: "https://open.spotify.com/track/4Eqw8jbMHNNgomuLmk6Fcg",
    isAnime: true,
    tuning: {
      name: "Open D#maj7",
      strings: "D# G D G A# D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0190674",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "crushcrushcrush",
    artist: "Paramore",
    youtube: "https://youtu.be/ZlNJ-zpCkxs",
    spotify: "https://open.spotify.com/track/7xpLGS6TyFYQfMy1XtPxps",
    isAnime: false,
    tuning: {
      name: "Open Cm",
      strings: "C G C G C D#",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0190606",
    },
    guitardex: "",
    difficulty: 7,
  },
  {
    title: "katharsis",
    source: "Tokyo Ghoul:re [OP2]",
    artist: "Toru Kitajima (TK)",
    youtube: "https://youtu.be/LiSKpS_u4PA",
    spotify: "https://open.spotify.com/track/6UPffF4elKqetjW0KVViZB",
    isAnime: true,
    tuning: {
      name: "Open C#",
      strings: "C# F C F C F",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0190504",
    },
    guitardex: "",
    difficulty: 7,
  },
  {
    title: "aLIEz",
    source: "Aldnoah.Zero [ED]",
    artist: "Hiroyuki Sawano",
    youtube: "https://youtu.be/Ex0teIbxpD4",
    spotify: "https://open.spotify.com/track/5LYLkig5PPtNFBNR3MSXlQ",
    isAnime: true,
    tuning: {
      name: "Open Cm",
      strings: "C G C G C D#",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0190288",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "Falling Down",
    artist: "Lil Peep, XXXTENTACION",
    youtube: "https://youtu.be/uTIFTIucyJ8",
    spotify: "https://open.spotify.com/track/08P7HOdZr1AO4Yr2KtfGlh",
    isAnime: false,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0190058",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "Wolves",
    artist: "Selena Gomez, Marshmello",
    youtube: "https://youtu.be/f6rlu66cBD0",
    spotify: "https://open.spotify.com/track/4ylBxNJHQRZuzl4MHMSJ1A",
    isAnime: false,
    tuning: {
      name: "Open C",
      strings: "C G C G C E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0190001",
    },
    guitardex: "",
    difficulty: 7,
  },
  {
    title: "breathin",
    artist: "Ariana Grande",
    youtube: "https://youtu.be/qTVytqxJkQ4",
    spotify: "https://open.spotify.com/track/6GFo1MLTw2K8b6AuJ3c0rF",
    isAnime: false,
    tuning: {
      name: "Open Cmaj9",
      strings: "C E D G B D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0189861",
    },
    guitardex: "",
    difficulty: 7,
  },
  {
    title: "lovely",
    artist: "Billie Eilish, Khalid",
    youtube: "https://youtu.be/pGVMkkXawyU",
    spotify: "https://open.spotify.com/track/1B2UMqJGtdV7ejh6Kg6tD4",
    isAnime: false,
    tuning: {
      name: "Open G/C",
      strings: "C G C G B D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0189102",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "Voracity",
    source: "Overlord III [OP]",
    artist: "MYTH & ROID",
    youtube: "https://youtu.be/KLsxfDzPw0E",
    isAnime: true,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0189189",
    },
    guitardex: "",
    difficulty: 8,
  },
  {
    title: "In My Feelings",
    artist: "Drake",
    youtube: "https://youtu.be/SVawEZ2XC3w",
    spotify: "https://open.spotify.com/track/3zDVTNHRUJYfsktDLIzg8v",
    isAnime: false,
    tuning: {
      name: "Open Cm",
      strings: "C G C G C D#",
    },
    button: {
      type: "buy",
      price: 4.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0188956",
    },
    guitardex: "",
    difficulty: 7, // Maybe 6
  },
  {
    title: "White Album",
    source: "White Album 2 [OST]",
    artist: "Elements Garden",
    youtube: "https://youtu.be/ZYTUE0y2qEE",
    spotify: "https://open.spotify.com/track/4B4MMDgigGcnFcUQx14Bew",
    isAnime: true,
    tuning: {
      name: "1/2 Step Down",
      strings: "D# G# C# F# A# D#",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0188838",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Sadness and Sorrow",
    source: "Naruto: Shippuden [OST]",
    artist: "Toshio Masuda, Musashi Purojekuto",
    youtube: "https://youtu.be/G-MZhNKszq4",
    spotify: "https://open.spotify.com/track/7n9EWtXm2er6MqmgatjtVT",
    isAnime: true,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0188156",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Grief and Sorrow",
    source: "Naruto: Shippuden [OST]",
    artist: "Toshio Masuda, Yasuharu Takanashi",
    spotify: "https://open.spotify.com/track/1waFJm6i8PTWpg08VeXdCb",
    isAnime: true,
    tuning: {
      name: "Open C",
      strings: "C G C G C E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0188006",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Loneliness",
    source: "Naruto: Shippuden [OST]",
    artist: "Yasuharu Takanashi",
    spotify: "https://open.spotify.com/track/4zZzctxMJt7tnBFbVfHspM",
    isAnime: true,
    tuning: {
      name: "Open Cm",
      strings: "C G C G C D#",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0188008",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Despair",
    source: "Naruto [OST]",
    artist: "Yasuharu Takanashi",
    spotify: "https://open.spotify.com/track/0gk60tLjDErXRqR3UQWaWP",
    isAnime: true,
    tuning: {
      name: "Open Cm",
      strings: "C G C G C D#",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0195999",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "The Raising Fighting Spirit",
    source: "Naruto [OST]",
    artist: "Toshio Masuda, Yasuharu Takanashi",
    spotify: "https://open.spotify.com/track/4HQcHeZX9Sg0ZHxC8H2FH6",
    isAnime: true,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0188009",
    },
    guitardex: "",
    difficulty: 8,
  },
  {
    title: "Guren Theme",
    source: "Naruto: Shippuden [OST]",
    artist: "Yasuharu Takanashi",
    spotify: "https://open.spotify.com/track/6hRvoKvQunuI8NMivcObkU",
    isAnime: true,
    tuning: {
      name: "Open Cm",
      strings: "C G C G C D#",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0188007",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "Experienced Many Battles",
    source: "Naruto: Shippuden [OST]",
    artist: "Yasuharu Takanashi",
    spotify: "https://open.spotify.com/track/3FnZIoU9EMZprMlKKy7Kie",
    isAnime: true,
    tuning: {
      name: "Drop D",
      strings: "D A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0187975",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "Sasuke's Ninja Way",
    source: "Naruto: Shippuden [OST]",
    artist: "Yasuharu Takanashi",
    youtube: "https://youtu.be/ca1Hipl3Kyc",
    spotify: "https://open.spotify.com/track/4yGxcBSyK0l1WBWNVJLrlN",
    isAnime: true,
    tuning: {
      name: "Drop D",
      strings: "D A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0187846",
    },
    guitardex: "",
    difficulty: 0,
  },
  {
    title: "Hope",
    artist: "XXXTENTACION",
    youtube: "https://youtu.be/aYgo9thr3cs",
    spotify: "https://open.spotify.com/track/69eIHSE6YPyUC4S46TMwCQ",
    isAnime: false,
    tuning: {
      name: "Open D#maj7",
      strings: "D# G D G A# D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0186285",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "no tears left to cry",
    artist: "Ariana Grande",
    youtube: "https://youtu.be/nhWjlMCMLI4",
    spotify: "https://open.spotify.com/track/0QiXOv4IwLQSkJH9QuyFtp",
    isAnime: false,
    tuning: {
      name: "Open D#maj7",
      strings: "D# G D G A# D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0187447",
    },
    guitardex: "",
    difficulty: 7,
  },
  {
    title: "Otherside",
    artist: "Post Malone",
    youtube: "https://youtu.be/CR3JVvHBzPU",
    isAnime: false,
    tuning: {
      name: "Open D#maj7",
      strings: "D# G D G A# D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0186093",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "Lemon",
    artist: "Kenshi Yonezu",
    youtube: "https://youtu.be/yWP5JsA_Rms",
    spotify: "https://open.spotify.com/track/4XXgFH6mgUt6cpITKd61rM",
    isAnime: false,
    tuning: {
      name: "Open B",
      strings: "B F# B F# B D#",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0185970",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "Jocelyn Flores",
    artist: "XXXTENTACION",
    youtube: "https://youtu.be/9CXa9RmZpsA",
    isAnime: false,
    tuning: {
      name: "Open Gm",
      strings: "D G D G A# D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0185239",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "Nevermind",
    artist: "Dennis Floyd",
    youtube: "https://youtu.be/Wufv-clNmsw",
    isAnime: false,
    tuning: {
      name: "Open A#sus2",
      strings: "A# F C F C C",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0185030",
    },
    guitardex: "",
    difficulty: 7,
  },
  {
    title: "Blue Bird",
    source: "Naruto: Shippuden [OP3]",
    artist: "Ikimonogakari",
    youtube: "https://youtu.be/FwoXpNCSMl8",
    spotify: "https://open.spotify.com/track/3ZZQuZSwNtNyt9l8KjhDOc",
    isAnime: true,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0184222",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "Ryusei",
    source: "Sword Art Online Alternative: Gun Gale Online [OP]",
    artist: "Eir Aoi",
    youtube: "https://youtu.be/5blMDh1gQdk",
    isAnime: true,
    tuning: {
      name: "Raise F",
      strings: "F A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0184106",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "Symphony",
    artist: "Clean Bandit, Zara Larsson",
    youtube: "https://youtu.be/QvCA5KnTLXg",
    spotify: "https://open.spotify.com/track/5rtzXUU0MaqUGYbU1yvTAc",
    isAnime: false,
    tuning: {
      name: "Open C",
      strings: "C G C G C E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0183916",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "Fatima",
    source: "Steins;Gate 0 [OP]",
    youtube: "https://youtu.be/xJYcLQxqQsM",
    isAnime: true,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0183748",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Here",
    source: "Mahoutsukai no Yome [OP]",
    artist: "JUNNA",
    youtube: "https://youtu.be/9xGjdh92QlQ",
    spotify: "https://open.spotify.com/track/2bsdZ4LLv2bmbSadFvq0wm",
    isAnime: true,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0183621",
    },
    guitardex: "",
    difficulty: 7,
  },
  {
    title: "God Knows",
    source: "The Melancholy of Haruhi Suzumiya [OST]",
    artist: "Aya Hirano",
    youtube: "https://youtu.be/tsya54Cerwc",
    isAnime: true,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0183553",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Ciao Adios",
    artist: "Anne-Marie",
    youtube: "https://youtu.be/O0RAAKa-EbQ",
    spotify: "https://open.spotify.com/track/3dsz3SC9vDlJ3cYvcxcjYR",
    isAnime: false,
    tuning: {
      name: "Open C",
      strings: "C G C G C E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0183031",
    },
    guitardex: "",
    difficulty: 7,
  },
  {
    title: "asphyxia",
    source: "Tokyo Ghoul:re [OP]",
    artist: "Co shu Nie",
    youtube: "https://youtu.be/G2HhXQPLrbo",
    spotify: "https://open.spotify.com/track/32iVl6KUiIvBDEFqohlp5V",
    isAnime: true,
    tuning: {
      name: "Open A#sus2",
      strings: "A# F C F C F",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0183369",
    },
    guitardex: "",
    difficulty: 9,
  },
  {
    title:
      "I Must Protect My Place / Now That This Old World Is Ending, Where the Morning Light Shines In, Come Wisdom and Come Fire",
    source: "Far Cry 5 Medley",
    artist: "Dan Romer",
    youtube: "https://youtu.be/rXEl8n1ILmo",
    isAnime: false,
    tuning: {
      name: "Raise F",
      strings: "F A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0183279",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Passionfruit",
    artist: "Drake",
    youtube: "https://youtu.be/X1L4SXbxqXI",
    spotify: "https://open.spotify.com/track/6HqKGWa3VrgyxztA2oNKFO",
    isAnime: false,
    tuning: {
      name: "Open Csus2",
      strings: "C G C G C D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0182998",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "changes",
    artist: "XXXTENTACION",
    youtube: "https://youtu.be/8iuSFiHMoeg",
    spotify: "https://open.spotify.com/track/4zwuNWlnojWlKKbS1CmUrz",
    isAnime: false,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0182903",
    },
    guitardex: "",
    difficulty: 4,
  },
  {
    title: "SAD!",
    artist: "XXXTENTACION",
    youtube: "https://youtu.be/xWL_eE-DjGo",
    spotify: "https://open.spotify.com/track/6otZnTJPkhZXAl6tVj5euo",
    isAnime: false,
    tuning: {
      name: "Drop D",
      strings: "D A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0182775",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Rick and Morty Theme Song",
    artist: "Ryan Elder",
    youtube: "https://youtu.be/AnIiiY9osEA",
    isAnime: false,
    tuning: {
      name: "Open A#m",
      strings: "A# F A# F A# C#",
    },
    button: {
      type: "buy",
      price: 5.79,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0182620",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "My Dearest",
    source: "Guilty Crown [OP]",
    artist: "Ryo (Supercell)",
    youtube: "https://youtu.be/oUmnLPI3xrY",
    spotify: "https://open.spotify.com/track/76EFsgLEMUmzHoxRKqpygu",
    isAnime: true,
    tuning: {
      name: "Raise F",
      strings: "F A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0182619",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "Congratulations",
    artist: "Post Malone",
    youtube: "https://youtu.be/fLDZiRe-iIc",
    spotify: "https://open.spotify.com/track/411vh6l9fIMhB9pU74ctCE",
    isAnime: false,
    tuning: {
      name: "Open C",
      strings: "C G C G C E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0182618",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "FRIENDS",
    artist: "Anne-Marie, Marshmello",
    youtube: "https://youtu.be/2GfakCspzHQ",
    spotify: "https://open.spotify.com/track/0t3DADP3XQ0ncjQVixkt2E",
    isAnime: false,
    tuning: {
      name: "Open D#maj7",
      strings: "D# G D G A# D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0182559",
    },
    guitardex: "",
    difficulty: 7,
  },
  {
    title: "Too Good At Goodbyes",
    artist: "Sam Smith",
    youtube: "https://youtu.be/WaxykZewSDU",
    spotify: "https://open.spotify.com/track/3UBiFC4Wpzmwpud8FOiLvy",
    isAnime: false,
    tuning: {
      name: "Open C",
      strings: "C G C G C E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0182530",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Dusk Till Dawn",
    artist: "Zayn, Sia",
    youtube: "https://youtu.be/0XNiXTUpspw",
    spotify: "https://open.spotify.com/track/75ThQx7I5b2Iryf0IqbKxI",
    isAnime: false,
    tuning: {
      name: "Open D#maj7",
      strings: "D# G D G A# D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0182478",
    },
    guitardex: "",
    difficulty: 7,
  },
  {
    title: "New Divide",
    artist: "Linkin Park",
    youtube: "https://youtu.be/r3TnS2mSn1U",
    spotify: "https://open.spotify.com/track/5yoU7gZzdhpHPZy7luHUHw",
    isAnime: false,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0182477",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Gucci Gang",
    artist: "Lil Pump",
    youtube: "https://youtu.be/B10miW6eohE",
    isAnime: false,
    tuning: {
      name: "Open Amadd11",
      strings: "A D C E A E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0182040",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "Uchiage Hanabi",
    source: "Uchiage Hanabi, Shita Kara Miru ka? Yoko Kara Miru ka? [ED]",
    artist: "DAOKO, Kenshi Yonezu",
    youtube: "https://youtu.be/sU8rlnKGG8Q",
    spotify: "https://open.spotify.com/track/5SGOudFmzp1oPwSUtz0ov5",
    isAnime: true,
    tuning: {
      name: "Open Bmaj9",
      strings: "B F# D# F# A# C#",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0182373",
    },
    guitardex: "",
    difficulty: 9,
  },
  {
    title: "The Last of Us Main Theme",
    artist: "Gustavo Santeollala",
    youtube: "https://youtu.be/CrltUZayrxQ",
    spotify: "https://open.spotify.com/track/0a2RNi29GqQbdqszJQfEEC",
    isAnime: false,
    tuning: {
      name: "1/2 Step Down",
      strings: "D# G# C# F# A# D#",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0182372",
    },
    guitardex: "",
    difficulty: 2,
  },
  {
    title: "Stranger Things Main Theme",
    artist: "Kyle Dixon, Michael Stein",
    youtube: "https://youtu.be/r38IE9yr5wk",
    spotify: "https://open.spotify.com/track/2EacBWFy9pdquKDj23px2s",
    isAnime: false,
    tuning: {
      name: "Open Amaj7",
      strings: "A A C# E G# E",
    },
    button: {
      type: "buy",
      price: 6.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0182371",
    },
    guitardex: "",
    difficulty: 2,
  },
  {
    title: "Shinzou wo Sasageyo!",
    source: "Attack on Titan Season 2 [OP]",
    artist: "Linked Horizon",
    youtube: "https://youtu.be/Hkl10-9_PLk",
    spotify: "https://open.spotify.com/track/737qRbscxtoZU4mNISYafl",
    isAnime: true,
    tuning: {
      name: "Open G",
      strings: "D G D G B D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0182370",
    },
    guitardex: "",
    difficulty: 7,
  },
  {
    title: "Something Just Like This",
    artist: "Chainsmokers, Coldplay",
    youtube: "https://youtu.be/rLnhfqcNFVQ",
    spotify: "https://open.spotify.com/track/2Ft1guAkFdsn1TdDW0FNEp",
    isAnime: false,
    tuning: {
      name: "Open D#maj7",
      strings: "D# G D G A# D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0182321",
    },
    guitardex: "https://gdex.cc/?Something-Just-Like-This_14.16.12.24.15.17.4.1.2",
    difficulty: 5,
  },
  {
    title: "Psycho",
    artist: "Post Malone",
    youtube: "https://youtu.be/7ppSIW4dnlQ",
    spotify: "https://open.spotify.com/track/4akPUrHU6Zie3yDqpNR2QP",
    isAnime: false,
    tuning: {
      name: "Open Dadd11",
      strings: "D G D F# A D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0182320",
    },
    guitardex: "",
    difficulty: 4,
  },
  {
    title: "Perfect",
    artist: "Ed Sheeran",
    youtube: "https://youtu.be/q9oXds-WVb4",
    spotify: "https://open.spotify.com/track/5QAetSWYn94tWXrjUg8fph",
    isAnime: false,
    tuning: {
      name: "Open C",
      strings: "C G C G C E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0182253",
    },
    guitardex: "https://gdex.cc/?Perfect_14.16.1.2.6.18",
    difficulty: 6,
  },
  {
    title: "God's Plan",
    artist: "Drake",
    youtube: "https://youtu.be/lBuULFGblKE",
    spotify: "https://open.spotify.com/track/2PH4ucaOZLvXFYpjlrLBky",
    isAnime: false,
    tuning: {
      name: "Open Gm",
      strings: "G G D G A# D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0182225",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "You Can Become A Hero!",
    source: "Boku no Hero Academia [OST]",
    artist: "Yuki Hayashi",
    youtube: "https://youtu.be/fOcJrJtSFRo",
    spotify: "https://open.spotify.com/track/1KeQ17eK5t1q7kKOwpRPEy",
    isAnime: true,
    tuning: {
      name: "Open D#maj7",
      strings: "D# G D G A# D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0182041",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "Sora ni Utaeba",
    source: "Boku no Hero Academia Season 2 [OP2]",
    artist: "Amazarashi",
    youtube: "https://youtu.be/soBUE3iK5DE",
    spotify: "https://open.spotify.com/track/7c83AvfOsfsQETwfHY2v7P",
    isAnime: true,
    tuning: {
      name: "Open C",
      strings: "C G C G C E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0182001",
    },
    guitardex: "",
    difficulty: 7,
  },
  {
    title: "Peace Sign",
    source: "Boku no Hero Academia Season 2 [OP]",
    artist: "Kenshi Yonezu",
    youtube: "https://youtu.be/IX4KhREj3ng",
    spotify: "https://open.spotify.com/track/6CQNWAqPhtljVYKAN5ugCx",
    isAnime: true,
    tuning: {
      name: "Open D#maj7",
      strings: "D# G D G A# D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0181963",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "Styx Helix",
    source: "Re:Zero [ED1]",
    artist: "MYTH & ROID",
    youtube: "https://youtu.be/6SBD2KywFpE",
    spotify: "https://open.spotify.com/track/1ES6L3gw6I97rp9nU8EWiN",
    isAnime: true,
    tuning: {
      name: "Open Cm",
      strings: "C G C G C D#",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0181957",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Unravel",
    source: "Tokyo Ghoul [OP]",
    artist: "Toru Kitajima (TK)",
    youtube: "https://youtu.be/WxOulfAfKvk",
    spotify: "https://open.spotify.com/track/3l6kDySxDhPwkPQ5Yx14cb",
    apple: "https://music.apple.com/us/album/unravel-op-from-tokyo-ghoul/1164616512?i=1164617002",
    isAnime: true,
    tuning: {
      name: "1/2 Step Down",
      strings: "D# G# C# F# A# D#",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0181875",
    },
    guitardex: "https://gdex.cc/?Unravel_16.17.15.24.6.11.18.4.5.19.1.2.28",
    difficulty: 7,
  },
  {
    title: "Believer",
    artist: "Imagine Dragons",
    youtube: "https://youtu.be/hXQxSi34GWY",
    spotify: "https://open.spotify.com/track/6bJjjnfcE55MIfg6lZiRUs",
    isAnime: false,
    tuning: {
      name: "Open A#m",
      strings: "A# F A# F A# C#",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0181874",
    },
    guitardex: "https://gdex.cc/?Believer_16.14.24.4.5.1.2.6.7.10.11.23",
    difficulty: 7,
  },
  {
    title: "rockstar",
    artist: "Post Malone, 21 Savage",
    youtube: "https://youtu.be/zvV4RH59lJ8",
    spotify: "https://open.spotify.com/track/44uZ4I5wV7v7Ec6w8ISiq9",
    isAnime: false,
    tuning: {
      name: "Open Dmaj7",
      strings: "D F# C# F# A C#",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0181804",
    },
    guitardex: "",
    difficulty: 7,
  },
  {
    title: "Your Reality",
    source: "Doki Doki Literature Club [OST]",
    artist: "Dan Salvato",
    youtube: "https://youtu.be/xsRZejd0YBs",
    spotify: "https://open.spotify.com/track/410hHJ74zIy9g6rQiMExGP",
    isAnime: false,
    tuning: {
      name: "Open C",
      strings: "C G C G C E",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0181757",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "The World",
    source: "Death Note [OP]",
    artist: "Nightmare",
    youtube: "https://youtu.be/_aLEhQ6KX2Q",
    spotify: "https://open.spotify.com/track/6pG7yxpLt08pUf3SgAikFu",
    isAnime: true,
    tuning: {
      name: "Standard",
      strings: "E A D G B E",
    },
    button: {
      type: "buy",
      price: 9.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0181754",
    },
    guitardex: "",
    difficulty: 5,
  },
  {
    title: "Shelter",
    artist: "Porter Robinson, Madeon",
    youtube: "https://youtu.be/NtOJw5DUrKw",
    spotify: "https://open.spotify.com/track/3XoItrDBRE7fxaWfklJH7n",
    isAnime: true,
    tuning: {
      name: "Open F#/B",
      strings: "B F# B F# A# C#",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0181716",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "Sincerely",
    source: "Violet Evergarden [OP]",
    artist: "TRUE, Shota Horie",
    youtube: "https://youtu.be/fPSZGQbzn9s",
    spotify: "https://open.spotify.com/track/3iEsEmTkhfYFkkA72RqCxg",
    isAnime: true,
    tuning: {
      name: "Open C",
      strings: "C G C G C E",
    },
    button: {
      type: "buy",
      price: 9.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0181678",
    },
    guitardex: "",
    difficulty: 6,
  },
  {
    title: "He's a Pirate (Main Theme)",
    source: "Pirates of the Carribean",
    artist: "Klaus Badelt, Hans Zimmer, Geoff Zanelli",
    youtube: "https://youtu.be/e_k-yLShHC8",
    spotify: "https://open.spotify.com/track/0DCmkHy3eZl8ht8OciCZk8",
    isAnime: false,
    tuning: {
      name: "Open Csus2",
      strings: "C G C G C D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0181043",
    },
    guitardex: "https://gdex.cc/?Hes-a-Pirate_16.14.6.18.4.5.19",
    difficulty: 5,
  },
  {
    title: "My Heart Will Go On",
    source: "Titanic",
    artist: "Celine Dion, James Horner",
    youtube: "https://youtu.be/hhxM3RJxJK0",
    isAnime: false,
    tuning: {
      name: "Open Csus2",
      strings: "C G C G C D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0181607",
    },
    guitardex: "https://gdex.cc/?My-Heart-Will-Go-On_14.16.1.2",
    difficulty: 5,
  },
  {
    title: "Despacito",
    artist: "Luis Fonsi, Justin Bieber, Daddy Yankee",
    youtube: "https://youtu.be/LNUcQ3QbqdY",
    spotify: "https://open.spotify.com/track/4ulyWajax5bYVmHV1nfOtu",
    isAnime: false,
    tuning: {
      name: "Open D#maj7",
      strings: "D# G D G A# D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0181567",
    },
    guitardex: "https://gdex.cc/?Despacito_16.14.17.24.1.2.4.5",
    difficulty: 6,
  },
  {
    title: "Shape of You",
    artist: "Ed Sheeran",
    youtube: "https://youtu.be/q3FgVVP_MKY",
    spotify: "https://open.spotify.com/track/4hvaxn5YowOMKv6jD2RE2h",
    isAnime: false,
    tuning: {
      name: "Open D#maj7",
      strings: "D# G D G A# D",
    },
    button: {
      type: "buy",
      price: 7.99,
      link: "https://www.musicnotes.com/sheetmusic/mtd.asp?ppn=MN0181493",
    },
    guitardex: "https://gdex.cc/?Shape-of-You_22.15.24.17.7.4.1.2",
    difficulty: 6,
  },

  // {
  //   title: "",
  //   source: "",
  //   artist: "",
  //   youtube: "",
  //   spotify: "",
  //   genre: "",
  //   tuning: {
  //     name: "Open ",
  //     strings: "",
  //   },
  //   button: {
  //     type: "buy",
  //     price: 7.99,
  //     link: "",
  //   },
  //   guitardex: "",
  // difficulty: 0,
  // },
];
